By : Rajdeep Ghosh, PhD Research Scholar, CSE-IITKGP

Reach out at [Linkedin](https://www.linkedin.com/in/ghoshrajdeep2000/) / Email: ghoshrajdeep2000@gmail.com

# **Python Syntax**
**Execute Python Syntax:** Python syntax can be executed by writing directly in the Command Line:


In [ ]:
print("Hello, World!")

Hello, World!


**Python Indentation:** Indentation refers to the spaces at the beginning of a code line. Where in other programming languages the indentation in code is for readability only, the indentation in Python is very important. Python uses indentation to indicate a block of code. The number of spaces is up to you as a programmer, but it has to be at least one.

In [ ]:
if 5 > 2:
  print("Five is greater than two!")

Five is greater than two!


**Syntax Error:** Python will give you an error if you skip the indentation.

In [ ]:
if 5 > 2:
print("Five is greater than two!")

IndentationError: ignored

**Comments:** Python has commenting capability for the purpose of in-code documentation.
1. Comments can be used to explain Python code.

2. Comments can be used to make the code more readable.

3. Comments can be used to prevent execution when testing code.

 Comments start with a #, and Python will render the rest of the line as a comment:

In [ ]:
#This is a comment.
print("Hello, World!")

Hello, World!


Comments can be placed at the end of a line, and Python will ignore the rest of the line or it can be even multi line comments


In [ ]:
print("Hello, World!") #This is a comment


#This is a multi line comment.
"""
This is a comment
written in
more than just one line
"""
print("Hello, World!")

Hello, World!
Hello, World!


**Print the addition, subtraction, multiplication, division, modulo, and exponentiation operations.**

In [ ]:
# Addition
print(19+2)

21


In [ ]:
# Subtraction
print(19-2)

17


In [ ]:
# Multiplication
print(19*2)

38


In [ ]:
# Division
print(19/2)

9.5


In [ ]:
# Exponentiation
19 ** 2

361

In [ ]:
# Modulo
19 % 2

1

# Create a variable

Variables are containers for storing data values.

In [ ]:
# Create a variable savings
savings = 100
# Print out savings
print(savings)

100



We have seen Python has no command for declaring a variable. A variable is created the moment you first assign a value to it.

In [ ]:
x = 5
y = "John"
print(x)
print(y)

5
John


Variables do not need to be declared with any particular type, and can even change type after they have been set.

In [ ]:
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)

Sally


**Casting**:
If you want to specify the data type of a variable, this can be done with casting.

In [ ]:
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

**Get the Type**: You can get the data type of a variable with the type() function.

In [ ]:
print(type(x))
print(type(y))
print(type(z))

<class 'str'>
<class 'int'>
<class 'float'>


**Quotation in Python:** Python accepts single ('), double (") and triple (''' or """) quotes to denote string literals, as long as the same type of quote starts and ends the string.

In [ ]:
x = "John"
# is the same as
x = 'John'
x = '''John'''
x = """John"""


print(x)

John


**Case-Sensitive:** Variable names are case-sensitive. The following examples will create two variables:

In [ ]:
a = 4
A = "Sally"
#A will not overwrite a
print(a)
print(A)

4
Sally


**Variable Names:** A variable can have a short name (like x and y) or a more descriptive name (age, carname, total_volume). Rules for Python variables:
1. A variable name must start with a letter or the underscore character.
2. A variable name cannot start with a number.
3. A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ ).
4. Variable names are case-sensitive (age, Age and AGE are three different variables).

In [ ]:
# Legal variable names:

myvar = "John"
my_var = "John"
_my_var = "John"
myVar = "John"
MYVAR = "John"
myvar2 = "John"

In [ ]:
#Illegal variable names:

2myvar = "John"
my-var = "John"
my var = "John"

SyntaxError: invalid decimal literal (ipython-input-3407628864.py, line 3)

**Multi Words Variable Names:** Variable names with more than one word can be difficult to read. There are several techniques you can use to make them more readable:

**Camel Case:** Each word, except the first, starts with a capital letter:

In [ ]:
myVariableName = "John"

**Pascal Case:** Each word starts with a capital letter:

In [ ]:
MyVariableName = "John"

**Snake Case:** Each word is separated by an underscore character:

In [ ]:
my_variable_name = "John"

**Many Values to Multiple Variables:** Python allows you to assign values to multiple variables in one line. Make sure the number of variables matches the number of values, or else you will get an error.

In [ ]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


**One Value to Multiple Variables:** You can assign the same value to multiple variables in one line.

In [ ]:
x = y = z = "Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


**Unpack a Collection:** If you have a collection of values in a list, tuple etc. Python allows you extract the values into variables. This is called unpacking.

In [ ]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


**Output Variables:** The Python print statement is often used to output variables. To combine both text and a variable, Python uses the + character:

In [ ]:
x = "awesome"
print("Python is " + x)

Python is awesome


You can also use the + character to add a variable to another variable:

In [ ]:
x = "Python is "
y = "awesome"
z =  x + y
print(z)

Python is awesome


For numbers, the + character works as a mathematical operator:

In [ ]:
x = 5
y = 10
print(x + y)

15


If you try to combine a string and a number, Python will give you an error:

In [ ]:
x = 5
y = "John"
print(x + y)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Global Variables:** Variables that are created outside of a function are known as global variables. Global variables can be used by everyone, both inside of functions and outside.
1. Create a variable outside of a function, and use it inside the function.

In [ ]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


If you create a variable with the same name inside a function, this variable will be local, and can only be used inside the function. The global variable with the same name will remain as it was, global and with the original value.
2. Create a variable inside a function, with the same name as the global variable.

In [ ]:
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome


**The global Keyword:** Normally, when you create a variable inside a function, that variable is local, and can only be used inside that function. To create a global variable inside a function, you can use the global keyword.

In [ ]:
def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic


Also, use the global keyword if you want to change a global variable inside a function.

In [ ]:
x = "awesome"

def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic


# Python Data Types



**Built-in Data Types:**
In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

Python has the following data types built-in by default, in these categories:

1. Text Type:	str
2. Numeric Types:	int, float, complex
3. Sequence Types:	list, tuple, range
4. Mapping Type:	dict
5. Set Types:	set, frozenset
6. Boolean Type:	bool
7. Binary Types:	bytes, bytearray, memoryview

**Getting the Data Type:**
You can get the data type of any object by using the type() function:

In [ ]:
x = 5
print(type(x))

<class 'int'>


**Setting the Data Type:**
In Python, the data type is set when you assign a value to a variable:

In [ ]:
x = "Hello World"

#display x:
print(x)

#display the data type of x:
print(type(x))


Hello World
<class 'str'>


In [ ]:
x = 20

#display x:
print(x)

#display the data type of x:
print(type(x))

20
<class 'int'>


In [ ]:
x = 20.5

#display x:
print(x)

#display the data type of x:
print(type(x))

20.5
<class 'float'>


In [ ]:
x = 1j

#display x:
print(x)

#display the data type of x:
print(type(x))


1j
<class 'complex'>


In [ ]:
x = ["apple", "banana", "cherry"]

#display x:
print(x)

#display the data type of x:
print(type(x))

['apple', 'banana', 'cherry']
<class 'list'>


In [ ]:
x = ("apple", "banana", "cherry")

#display x:
print(x)

#display the data type of x:
print(type(x))


('apple', 'banana', 'cherry')
<class 'tuple'>


In [ ]:
x = range(6)

#display x:
print(x)

#display the data type of x:
print(type(x))


range(0, 6)
<class 'range'>


In [ ]:
x = {"name" : "John", "age" : 36}

#display x:
print(x)

#display the data type of x:
print(type(x))

{'name': 'John', 'age': 36}
<class 'dict'>


In [ ]:
x = {"apple", "banana", "cherry"}

#display x:
print(x)

#display the data type of x:
print(type(x))


{'cherry', 'apple', 'banana'}
<class 'set'>


In [ ]:
x = True

#display x:
print(x)

#display the data type of x:
print(type(x))


True
<class 'bool'>


**Python Numbers:** There are three numeric types in Python: int, float and complex. Variables of numeric types are created when you assign a value to them:

In [ ]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


**Int:** Int, or integer, is a whole number, positive or negative, without decimals, of unlimited length.

In [ ]:
x = 1
y = 35656222554887711
z = -3255522

print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


**Float:** Float, or "floating point number" is a number, positive or negative, containing one or more decimals.

In [ ]:
x = 1.10
y = 1.0
z = -35.59

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


Float can also be scientific numbers with an "e" to indicate the power of 10.

In [ ]:
x = 35e3
y = 12E4
z = -87.7e100

print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


**Type Conversion:** You can convert from one type to another with the int(), float(), and complex() methods.

In [ ]:
x = 1    # int
y = 2.8  # float
z = 1j   # complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)



print(a)
print(b)


print(type(a))
print(type(b))


1.0
2
<class 'float'>
<class 'int'>


**Note:** You cannot convert complex numbers into another number type.

**Random Number:**
Python does not have a random() function to make a random number, but Python has a built-in module called random that can be used to make random numbers.Import the random module, and display a random number between 1 and 9:

In [ ]:
import random

print(random.randrange(1, 10))

8


# Basic of iterations


Why Do We Need Loops?

Imagine printing numbers from 1 to 5 Without loops

In [ ]:
print(1)
print(2)
print(3)
print(4)
print(5)

1
2
3
4
5



With loops


In [ ]:
for i in range(1, 6):
    print(i)

# Loops allow us to **repeat actions automatically**.

1
2
3
4
5



## The `for` Loop

A `for` loop is used to iterate over a sequence (list, string, range,
etc.).

### Basic Syntax

``` python
for variable in sequence:
    # code block
```

### Example: Loop over numbers

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


Example 2: Loop over a list

In [ ]:
fruits = ["apple", "banana", "mango"]

for fruit in fruits:
    print(fruit)

apple
banana
mango


Example 3: Loop over a string


In [ ]:
for ch in "Python":
    print(ch)

P
y
t
h
o
n



## Loop Control Statements

### `break` --- stop the loop early

### `continue` --- skip one iteration




In [ ]:
for i in range(10):
    if i == 5:
        break # Stops when `i` becomes 5.
    print(i)




0
1
2
3
4


In [ ]:
for i in range(5):
    if i == 2:
        continue # Skips printing `2`.
    print(i)

0
1
3
4




------------------------------------------------------------------------

## What is an Iterator?

An **iterator** is an object that lets you go through items **one at a
time**.

Python loops internally use iterators.

### Example: Iterator from a list


👉 `iter()` creates an iterator
👉 `next()` gives the next value.

In [ ]:
numbers = [10, 20, 30]

it = iter(numbers)   # create iterator

print(next(it))
print(next(it))
print(next(it))

10
20
30


In [ ]:
# 7. Practical Example

# Sum all numbers in a list.


nums = [1, 2, 3, 4, 5]
total = 0

for n in nums:
    total += n

print("Sum =", total)


Sum = 15


# Python Strings

**Strings are Arrays:**
Like many other popular programming languages, strings in Python are arrays of bytes representing unicode characters.

However, Python does not have a character data type, a single character is simply a string with a length of 1.

Square brackets can be used to access elements of the string. Get the character at position 1 (remember that the first character has the position 0):

In [ ]:
a = "Hello, World!"
print(a[1])

e


**Looping Through a String:**
Since strings are arrays, we can loop through the characters in a string, with a for loop. Loop through the letters in the word "banana".

In [ ]:
for x in "banana":
  print(x)

b
a
n
a
n
a


**String Length:** To get the length of a string, use the len() function.

In [ ]:
a = "Hello, World!"
print(len(a))

13


**Python - Slicing Strings:** You can return a range of characters by using the slice syntax.

Specify the start index and the end index, separated by a colon, to return a part of the string.

Get the characters from position 2 to position 5 (not included).

In [ ]:
b = "Hello, World!"
print(b[2:5])

llo


**Slice From the Start:** By leaving out the start index, the range will start at the first character. Get the characters from the start to position 5 (not included):

In [ ]:
b = "Hello, World!"
print(b[:5])

Hello


**Slice To the End:** By leaving out the end index, the range will go to the end. Get the characters from position 2, and all the way to the end:

In [ ]:
b = "Hello, World!"
print(b[2:])

llo, World!


**Negative Indexing:** Use negative indexes to start the slice from the end of the string. Get the characters.

From: "o" in "World!" (position -5)

To, but not included: "d" in "World!" (position -2):

In [ ]:
b = "Hello, World!"
print(b[-5:-2])

orl


## Strings - Modify Strings
Python has a set of built-in methods that you can use on strings.

**Upper Case:** The upper() method returns the string in upper case.


In [ ]:
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!


**Lower Case:** The lower() method returns the string in lower case.

In [ ]:
a = "Hello, World!"
print(a.lower())

hello, world!


**Remove Whitespace:** Whitespace is the space before and/or after the actual text, and very often you want to remove this space. The strip() method removes any whitespace from the beginning or the end.

In [ ]:
a = " Hello, World! "
print(a.strip())

Hello, World!


**Replace String:** The replace() method replaces a string with another string.

In [ ]:
a = "Hello, World!"
print(a.replace("H", "J"))

Jello, World!


**Split String:** The split() method returns a list where the text between the specified separator becomes the list items.

In [ ]:
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']

['Hello', ' World!']


## Strings - String Concatenation
To concatenate, or combine, two strings you can use the + operator. Merge variable a with variable b into variable c:

In [ ]:
a = "Hello"
b = "World"
c = a + b
print(c)

HelloWorld


To add a space between them, add a " ":

In [ ]:
a = "Hello"
b = "World"
c = a + " " + b
print(c)

Hello World


## Strings - Format Strings
As we learned in the Python Variables section, we cannot combine strings and numbers like this:

In [ ]:
age = 36
txt = "My name is John, I am " + age
print(txt)

TypeError: can only concatenate str (not "int") to str

But we can combine strings and numbers by using the format() method!

The format() method takes the passed arguments, formats them, and places them in the string where the placeholders {} are:

In [ ]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollars.


You can use index numbers {0} to be sure the arguments are placed in the correct placeholders:

In [ ]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


**Escape Character:**
To insert characters that are illegal in a string, use an escape character.

An escape character is a backslash \ followed by the character you want to insert.

An example of an illegal character is a double quote inside a string that is surrounded by double quotes.You will get an error if you use double quotes inside a string that is surrounded by double quotes:

In [ ]:
txt = "We are the so-called "Vikings" from the north."

SyntaxError: invalid syntax (ipython-input-7934146.py, line 1)

To fix this problem, use the \ (escape  character). The escape character allows you to use double quotes when you normally would not be allowed.

In [ ]:
txt = "We are the so-called \"Vikings\" from the north."
print(txt)


We are the so-called "Vikings" from the north.


**Escape Characters:**
Other escape characters used in Python:

In [ ]:
#Single Quote \'
txt = 'It\'s alright.'
print(txt)


It's alright.


In [ ]:
#Backslash
txt = "This will insert one \\ (backslash)."
print(txt)


This will insert one \ (backslash).


In [ ]:
#NewLine
txt = "Hello\nWorld!"
print(txt)


Hello
World!


In [ ]:
#Tab \t
txt = "Hello\tWorld!"
print(txt)

Hello	World!


In [ ]:
#backspace \b
txt = "Hello \bWorld!"
print(txt)

Hello World!


When you run a condition in an if statement, Python returns True or False. Print a message based on whether the condition is True or False:

In [ ]:
a = 200
b = 33

if b > a:
  print("b is greater than a")
else:
  print("b is not greater than a")

b is not greater than a


In [ ]:
print(b>a)

False


**Evaluate Values and Variables:** The bool() method is used to return or convert a value to a Boolean value i.e., True or False, using the standard truth testing procedure. The bool() method in general takes only one parameter(here x), on which the standard truth testing procedure can be applied. If no parameter is passed, then by default it returns False. So, passing a parameter is optional. It can return one of the two values.

1. It returns True if the parameter or value passed is True.
2. It returns False if the parameter or value passed is False.

Here are a few cases, in which Python’s bool() method returns false. Except these all other values return True.

1. If a False value is passed.
2. If None is passed.
3. If an empty sequence is passed, such as (), [], ”, etc
4. If Zero is passed in any numeric type, such as 0, 0.0 etc
5. If an empty mapping is passed, such as {}.
6. If Objects of Classes having __bool__() or __len()__ method, returning 0 or False.

The bool() function allows you to evaluate any value, and give you True or False in return. Evaluate a string and a number:

In [ ]:
print(bool("Hello"))
print(bool(15))

True
True


Evaluate two variables:

In [ ]:
x = "Hello"
y = 15

print(bool(x))
print(bool(y))

True
True


**Most Values are True:** Almost any value is evaluated to True if it has some sort of content.

Any string is True, except empty strings.

Any number is True, except 0.

Any list, tuple, set, and dictionary are True, except empty ones.

In [ ]:
print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))

True
True
True


**Functions can Return a Boolean:** You can create functions that returns a Boolean Value. Print the answer of a function:

In [ ]:
def myFunction() :
  return True

print(myFunction())

True


Print "YES!" if the function returns True, otherwise print "NO!":

In [ ]:
def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")

YES!


Python also has many built-in functions that return a boolean value, like the isinstance() function, which can be used to determine if an object is of a certain data type. Check if an object is an integer or not:

In [ ]:
x = 200
print(isinstance(x, int))

True


# Python Functions

A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.

A function can return data as a result.

**Creating a Function:**
In Python a function is defined using the def keyword:

In [ ]:
def my_function():
  print("Hello from a function")

**Calling a Function**:
To call a function, use the function name followed by parenthesis:

In [ ]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


**Arguments**:
Information can be passed into functions as arguments.

Arguments are specified after the function name, inside the parentheses. You can add as many arguments as you want, just separate them with a comma.

The following example has a function with one argument (fname). When the function is called, we pass along a first name, which is used inside the function to print the full name:

In [ ]:
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

Emil Refsnes
Tobias Refsnes
Linus Refsnes


Arguments are often shortened to args in Python documentations.

**Parameters or Arguments?**

The terms parameter and argument can be used for the same thing: information that are passed into a function.

From a function's perspective:

A parameter is the variable listed inside the parentheses in the function definition.

An argument is the value that is sent to the function when it is called.

**Number of Arguments**:
By default, a function must be called with the correct number of arguments. Meaning that if your function expects 2 arguments, you have to call the function with 2 arguments, not more, and not less.

In [ ]:
def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil", "Refsnes")

Emil Refsnes


**Error**:  If you try to call the function with 1 or 3 arguments, you will get an error:

In [ ]:
#This function expects 2 arguments, but gets only 1:

def my_function(fname, lname):
  print(fname + " " + lname)

my_function("Emil")

TypeError: my_function() missing 1 required positional argument: 'lname'

## Arbitrary Arguments *args:
If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.

This way the function will receive a tuple of arguments, and can access the items accordingly:

In [ ]:
def my_function(*kids):
  print("The youngest child is " + kids[2])

my_function("Emil", "Tobias", "Linus")

The youngest child is Linus


**Keyword Arguments**:
You can also send arguments with the key = value syntax.

This way the order of the arguments does not matter.

In [ ]:
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")

The youngest child is Linus


**Arbitrary Keyword Arguments**  (***kwargs) :
If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.

This way the function will receive a dictionary of arguments, and can access the items accordingly:

In [ ]:
def my_function(**kid):
  print("His last name is " + kid["lname"])

my_function(fname = "Tobias", lname = "Refsnes")

His last name is Refsnes


**Default Parameter Value**:
The following example shows how to use a default parameter value.

If we call the function without argument, it uses the default value:

In [ ]:
def my_function(country = "Norway"):
  print("I am from " + country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Brazil")

I am from Sweden
I am from India
I am from Norway
I am from Brazil


**Passing a List as an Argument**:
You can send any data types of argument to a function (string, number, list, dictionary etc.), and it will be treated as the same data type inside the function.

E.g. if you send a List as an argument, it will still be a List when it reaches the function:

In [ ]:
def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

apple
banana
cherry


**Return Values**:
To let a function return a value, use the return statement:

In [ ]:
def my_function(x):
  return 5 * x

print(my_function(3))
print(my_function(5))
print(my_function(9))

15
25
45


**The pass Statement**:
Function definitions cannot be empty, but if you for some reason have a function definition with no content, put in the pass statement to avoid getting an error.

In [ ]:
def myfunction():
  pass

**Recursion**:
Python also accepts function recursion, which means a defined function can call itself.

Recursion is a common mathematical and programming concept. It means that a function calls itself. This has the benefit of meaning that you can loop through data to reach a result.

The developer should be very careful with recursion as it can be quite easy to slip into writing a function which never terminates, or one that uses excess amounts of memory or processor power. However, when written correctly recursion can be a very efficient and mathematically-elegant approach to programming.

In this example, tri_recursion() is a function that we have defined to call itself ("recurse"). We use the k variable as the data, which decrements (-1) every time we recurse. The recursion ends when the condition is not greater than 0 (i.e. when it is 0).

To a new developer it can take some time to work out how exactly this works, best way to find out is by testing and modifying it.

In [ ]:
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)



Recursion Example Results
1
3
6
10
15
21


21

**Python Lambda**:
A lambda function is a small anonymous function.

A lambda function can take any number of arguments, but can only have one expression.

**Syntax**
lambda arguments : expression

In [ ]:
#Add 10 to argument a, and return the result:

x = lambda a : a + 10
print(x(5))

15


Lambda functions can take any number of arguments:

In [ ]:
#Multiply argument a with argument b and return the result:

x = lambda a, b : a * b
print(x(5, 6))

30


**Why Use Lambda Functions?**
The power of lambda is better shown when you use them as an anonymous function inside another function.

Say you have a function definition that takes one argument, and that argument will be multiplied with an unknown number:

In [ ]:
def myfunc(n):
  return lambda a : a * n

In [ ]:
#Use that function definition to make a function that always doubles the number you send in:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


# Python Arrays & classes
Python does not have built-in support for Arrays, but Python Lists can be used instead. Arrays are used to store multiple values in one single variable.

In [ ]:
#Create an array containing car names:

cars = ["Ford", "Volvo", "BMW"]

**What is an Array?**
An array is a special variable, which can hold more than one value at a time.

If you have a list of items (a list of car names, for example), storing the cars in single variables could look like this:

In [ ]:
car1 = "Ford"
car2 = "Volvo"
car3 = "BMW"

However, what if you want to loop through the cars and find a specific one? And what if you had not 3 cars, but 300?

The solution is an array!

An array can hold many values under a single name, and you can access the values by referring to an index number.

**Access the Elements of an Array**
You refer to an array element by referring to the index number.

In [ ]:
#Get the value of the first array item:

x = cars[0]
print(x)

Ford


In [ ]:
#Modify the value of the first array item:

cars[0] = "Toyota"
print(cars[0])

Toyota


**The Length of an Array**:
Use the len() method to return the length of an array (the number of elements in an array).

In [ ]:
#Return the number of elements in the cars array:

x = len(cars)
print(x)

3


**Looping Array Elements**:

You can use the for in loop to loop through all the elements of an array.

In [ ]:
#Print each item in the cars array:

for x in cars:
  print(x)

Toyota
Volvo
BMW


**Adding Array Elements**:

You can use the append() method to add an element to an array.

In [ ]:
#Add one more element to the cars array:
cars = ["Ford", "Volvo", "BMW"]

cars.append("Honda")

print(cars)


['Ford', 'Volvo', 'BMW', 'Honda']


**Removing Array Elements**:

You can use the pop() method to remove an element from the array.

In [ ]:
#Delete the second element of the cars array:

cars.pop(1)

'Volvo'

You can also use the remove() method to remove an element from the array.

In [ ]:
#Delete the element that has the value "Ford":
cars = ["Ford", "Volvo", "BMW"]
cars.remove("Ford")
print(cars)

['Volvo', 'BMW']


**Python Classes and Objects**: Python is an object oriented programming language.

Almost everything in Python is an object, with its properties and methods.

A Class is like an object constructor, or a "blueprint" for creating objects.

**Create a Class**:
To create a class, use the keyword class:

In [ ]:
#Create a class named MyClass, with a property named x:

class MyClass:
  x = 5

**Create Object**:
Now we can use the class named MyClass to create objects:

In [ ]:
#Create an object named p1, and print the value of x:

p1 = MyClass()
print(p1.x)

5


**The __init__() Function**:
The examples above are classes and objects in their simplest form, and are not really useful in real life applications.

To understand the meaning of classes we have to understand the built-in __init__() function.

All classes have a function called __init__(), which is always executed when the class is being initiated.

Use the __init__() function to assign values to object properties, or other operations that are necessary to do when the object is being created:

In [ ]:
#Create a class named Person, use the __init__() function to assign values for name and age:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


**Object Methods**:
Objects can also contain methods. Methods in objects are functions that belong to the object.

Let us create a method in the Person class:

In [ ]:
#Insert a function that prints a greeting, and execute it on the p1 object:

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def myfunc(self):
    print("Hello my name is " + self.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


**The self Parameter**:
The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:

In [ ]:
#Use the words mysillyobject and abc instead of self:

class Person:
  def __init__(mysillyobject, name, age):
    mysillyobject.name = name
    mysillyobject.age = age

  def myfunc(abc):
    print("Hello my name is " + abc.name)

p1 = Person("John", 36)
p1.myfunc()

Hello my name is John


**Modify Object Properties**:
You can modify properties on objects like this:

In [ ]:
#Set the age of p1 to 40:

p1.age = 40
print(p1.age)

40


**Delete Object Properties**:
You can delete properties on objects by using the del keyword:

In [ ]:
#Delete the name property from the p1 object:

del p1.name

**Delete Objects**:
You can delete objects by using the del keyword:

In [ ]:
#Delete the p1 object:

del p1

# Python Modules

Consider a module to be the same as a code library.

A file containing a set of functions you want to include in your application.


**Use of Python Modules**: In the following examples, you will experience frequent use of Python Modules.

**Python Dates**:
A date in Python is not a data type of its own, but we can import a module named datetime to work with dates as date objects.

In [ ]:
import datetime

x = datetime.datetime.now()
print(x)

2021-06-27 05:53:30.220046


**Date Output**:
When we execute the code from the example above the result will be:

2021-06-27 11:19:50.935821
The date contains year, month, day, hour, minute, second, and microsecond.

The datetime module has many methods to return information about the date object.

Here are a few examples

In [ ]:
#Return the year and name of weekday:
import datetime

x = datetime.datetime.now()

print(x.year)
print(x.strftime("%A"))

2021
Sunday


**Creating Date Objects**:
To create a date, we can use the datetime() class (constructor) of the datetime module. The datetime() class requires three parameters to create a date: year, month, day.

In [ ]:
import datetime

x = datetime.datetime(2020, 5, 17)

print(x)

2020-05-17 00:00:00


The datetime() class also takes parameters for time and timezone (hour, minute, second, microsecond, tzone), but they are optional, and has a default value of 0, (None for timezone).



**Python Math**

Python has a set of built-in math functions, including an extensive math module, that allows you to perform mathematical tasks on numbers. The min() and max() functions can be used to find the lowest or highest value in an iterable:

In [ ]:
x = min(5, 10, 25)
y = max(5, 10, 25)

print(x)
print(y)

5
25


The abs() function returns the absolute (positive) value of the specified number:

In [ ]:
x = abs(-7.25)

print(x)

7.25


The pow(x, y) function returns the value of x to the power of y.

In [ ]:
x = pow(4, 3)

print(x)

64


**The Math Module:**
Python has also a built-in module called math, which extends the list of mathematical functions.

To use it, you must import the math module:

In [ ]:
import math

When you have imported the math module, you can start using methods and constants of the module.

The math.sqrt() method for example, returns the square root of a number:

In [ ]:
import math

x = math.sqrt(64)

print(x)

8.0


The math.ceil() method rounds a number upwards to its nearest integer, and the math.floor() method rounds a number downwards to its nearest integer, and returns the result:

In [ ]:
import math

x = math.ceil(1.4)
y = math.floor(1.4)

print(x) # returns 2
print(y) # returns 1

2
1


The math.pi constant, returns the value of PI (3.14...):

In [ ]:
import math

x = math.pi

print(x)

3.141592653589793


# More on Python lists


**Create a list**

As opposed to int, bool etc., a list is a compound data type; you can group values together:


In [ ]:
a = "is"
b = "nice"
my_list = ["my", "list", a, b]
print(my_list)

['my', 'list', 'is', 'nice']


After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables for now, as shown in the script.

**Create a list, areas, that contains the area of the hallway (hall), kitchen (kit), living room (liv), bedroom (bed) and bathroom (bath), in this order. Use the predefined variables. Print areas with the print() function.**

In [ ]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)


[11.25, 18.0, 20.0, 10.75, 9.5]


A list can contain any Python type. Although it's not really common, a list can also contain a mix of Python types including strings, floats, booleans, etc.

The printout of the previous exercise wasn't really satisfying. It's just a list of numbers representing the areas, but you can't tell which area corresponds to which part of your house.

The code on the right is the start of a solution. For some of the areas, the name of the corresponding room is already placed in front. Pay attention here! "bathroom" is a string, while bath is a variable that represents the float 9.50 you specified earlier.
**Finish the line of code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations. Print areas again; is the printout more informative this time?**

In [ ]:
# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


**List of lists**

As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.

Instead of creating a flat list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. The script on the right can already give you an idea.

Don't get confused here: "hallway" is a string, while hall is a variable that represents the float 11.25 you specified earlier.
**Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order! Print out house; does this way of structuring your data make more sense? Print out the type of house. Are you still dealing with a list?**


In [ ]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]

# Print out house


# Print out the type of house


 **Subset and conquer**

Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

In [ ]:
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!

'b'

Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?
**Print out the second element from the areas list (it has the value 11.25).
Subset and print out the last element of areas, being 9.50. Using a negative index makes sense here!
Select the number representing the area of the living room (20.0) and print it out.**

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


**Subset and calculate**

After you've extracted values from a list, you can use them to perform additional calculations. Take this example, where the second and fourth element of a list x are extracted. The strings that result are pasted together using the + operator:


In [ ]:
x = ["a", "b", "c", "d"]
print(x[1] + x[3])

bd


**Using a combination of list subsetting and variable assignment, create a new variable, eat_sleep_area, that contains the sum of the area of the kitchen and the area of the bedroom. Print the new variable eat_sleep_area.**

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

In [ ]:
my_list[start:end]

The start index will be included, while the end index is not.

The code sample below shows an example. A list with "b" and "c", corresponding to indexes 1 and 2, are selected from a list x:

In [ ]:
x = ["a", "b", "c", "d"]
x[1:3]

['b', 'c']

**Use slicing to create a list, downstairs, that contains the first 6 elements of areas. Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas. Print both downstairs and upstairs using print().**

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[6:10]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
# Alternative slicing to create downstairs
downstairs = areas[:6]
print(downstairs)

# Alternative slicing to create upstairs
upstairs = areas[6:]
print(upstairs)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


## **Replace list elements**
Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once. Use the IPython Shell to experiment with the commands below.


In [ ]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]
print(x)

['a', 'r', 's', 't']


**Update the area of the bathroom area to be 10.50 square meters instead of 9.50.
Make the areas list more trendy! Change "living room" to "chill zone".**

In [ ]:
# Correct the bathroom area
areas[-1] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


## **Extend a list**
If you can change elements in a list, you sure want to be able to add elements to it, right? You can use the + operator.
**Use the + operator to paste the list ["poolhouse", 24.5] to the end of the areas list. Store the resulting list as areas_1. Further extend areas_1 by adding data on your garage. Add the string "garage" and float 15.45. Name the resulting list areas_2.**

In [ ]:
# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5]
print(areas_1)

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ["garage", 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


## **Delete list elements**
You can also remove elements from your list. You can do this with the del statement:

In [ ]:
x = ["a", "b", "c", "d"]
del(x[1])
print(x)

['a', 'c', 'd']


Pay attention here: as soon as you remove an element from a list, the indexes of the elements that come after the deleted element all change!

## **Inner workings of lists**
The Python code in the script already creates a list with the name areas and a copy named areas_copy. Next, the first element in the areas_copy list is changed and the areas list is printed out. If you hit Run Code you'll see that, although you've changed areas_copy, the change also takes effect in the areas list. That's because areas and areas_copy point to the same list.

If you want to prevent changes in areas_copy from also taking effect in areas, you'll have to do a more explicit copy of the areas list. You can do this with list() or by using [:].


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = areas

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[5.0, 18.0, 20.0, 10.75, 9.5]


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create areas_copy
areas_copy = list(areas)

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]
